---
ci:
  # We rely on renovate to update it but there is no way to fully disable it
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_schedule: quarterly
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.17
    hooks:
      - id: uv-sync
      - id: uv-lock
        name: "deps: upgrade via uv sync --upgrade"
        alias: deps
        args: ["--upgrade"]
        stages: [manual]
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.2.0
    hooks:
      - id: cspell
        entry: bash
        pass_filenames: false
        args:
          [
            "-euo",
            "pipefail",
            "-c",
            "cspell-cli . --relative --no-progress --no-summary && cspell-cli . --disable-dictionary=words --no-exit-code --words-only --quiet --unique | LC_ALL=C sort > .config/dictionary.txt",
          ]
        name: cspell + remove unused and sort dictionary
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma.git
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-sort-json

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort-fix
        alias: toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-format
        alias: ruff
      - id: ruff-check
        alias: ruff

  - repo: https://github.com/jsh9/pydoclint
    rev: "0.7.3"
    hooks:
      - id: pydoclint
        # This allows automatic reduction of the baseline file when needed.
        entry: sh -ec "pydoclint . && pydoclint --generate-baseline=1 ."
        pass_filenames: false

  - repo: https://github.com/pycqa/pylint.git
    rev: v3.3.8
    hooks:
      - id: pylint
        args:
          - --output-format=colorized
        additional_dependencies:
          - argcomplete
          - pytest
          - pyyaml
          - subprocess_tee
          - setuptools
          - tox

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.18.1
    hooks:
      - id: mypy
        additional_dependencies:
          - argcomplete
          - pip
          - pytest
          - subprocess_tee
          - types-pyyaml
          - uv
        # Override default pre-commit '--ignore-missing-imports'
        args: [--strict]
