---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma.git
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.4
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: v4.0.0-alpha.4
    hooks:
      - id: prettier
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
          - prettier-plugin-sort-json

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.7"
    hooks:
      - id: ruff
        args:
          - "--exit-non-zero-on-fix"

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.1.1
    hooks:
      - id: cspell
        name: Spell check with cspell

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.3.8
    hooks:
      - id: pydoclint
        args:
          - "--config=pyproject.toml"

  - repo: https://github.com/pycqa/pylint.git
    rev: v3.0.1
    hooks:
      - id: pylint
        args:
          - --output-format=colorized
        additional_dependencies:
          - pytest
          - pyyaml
          - subprocess_tee
          - setuptools
          - tox

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest
          - subprocess_tee
          - tox
          - types-PyYAML
          - types-setuptools
        args:
          - src
          - tests
          - --python-version=3.11
        pass_filenames: false
