---
version: 2

mkdocs:
  fail_on_warning: true
  configuration: mkdocs.yml

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - python3 -m pip install --user tox
    - python3 -m tox -e docs
submodules:
  include: all
  recursive: true
