dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - en_US
  - python
  - python-common
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
enabled: true
useGitignore: true
ignorePaths:
  - "*.egg-info"
  - .config/dictionary.txt
  - cspell.config.yaml
  - junit.xml
  - mkdocs.yml
  - pyproject.toml
  - site
  - uv.lock

languageSettings:
  - languageId: python
    allowCompoundWords: false
